site_name: GhostVerse
site_url: https://i-am-ghost.github.io/GhostVerse/

nav:
  - ğŸ  Home: index.md
  - ğŸ“š Foundations: foundations.md
  - ğŸ¦¸ Interview : interview.md
  - ğŸ“ Contact Us: contacts.md
  

theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    font:
      text: Roboto
    hljs_languages:
      - yaml
      - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    logo: img/favicon.ico
    favicon: img/logo.png

extra:
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

spec:
  source: 
    git:
      ref: GhostVerse
      url: https://github.com/i-Am-GhOsT/GhostVerse

